class EasmReportError(Exception): ...
class ParseError(EasmReportError): ...
class ValidationError(EasmReportError): ...
class PathTraversalError(EasmReportError): ...
class InvalidFileTypeError(EasmReportError): ...
class FileTooLargeError(EasmReportError): ...
